# Generated by Django 2.2.4 on 2019-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
