# Generated by Django 2.2.4 on 2019-10-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
